### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by LucasMahieu** [meninge/diplo-docu#2]
- [ ]  Présentation démo
- [ ] Conclusion
- [ ] Manuel utilisateur 
- [x] Validation neurone
- [x] Caractéristique finale 
- [x] Conception fsm et recode
- [x] Conception nnlayer
- [x] Schéma des pops (dans vérif sur carte)
- [x] Évaluation théorique
- [x] Mettre au propre le code
- [x]  commentaire dans code VHDL (A améliorer ?)
- [x]  Commentaire des fonctions en C (pas de commentaire, ou très peu DANS les fonctions)
- [x] Ecrire partie de conception du pipeline total du réseau pour parler des fifos (schéma)
- [ ] Opti FSM si temps restant (x2 à gagner quand même)
- [x] Partie Remerciements
- [x] Partie implantation sur carte dans caractéristiques ...
- [ ] Parler des problèmes dans la partie planning et répartition des tâches
- [x] supprimer toutes les occurrences du test avec 200 neurones.

**Comment by LucasMahieu** [comment]
Lucas : vérif neurone, schema pop + nnlayer + token + scan chain, présentation démo, pipeline complet (schema)
Paul : Conception recode et fsm :heavy_check_mark: , commentaire vhdl :heavy_check_mark:, caractéristique finale :heavy_check_mark: , éval théorique :heavy_check_mark: 
Hugues : NNLayer (Il faut parler du distribuf = expliquer pq on s'en sert et rapidement comment il fonctionne , on peut te faire un schema si besoin) , conclu, mise au propre du code
