### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by LucasMahieu** [meninge/diplo-docu#3]
- [x] Lucas : Faire présentation de la démo
- [x] Lucas: Finir la fonction de démo pour printer les ASCII digits
- [x] Lucas: Problèmes rencontrés
- [x] Lucas: Relire 
- [x] Paul: Conclusion
- [x] Paul: Latex : lien hyper text 
- [x] Paul: Manuel utilisateur HW (vivado ajouter une IP voir slack)
- [x] Paul: Planning réel (vs prévisionnel)
- [x] Paul: Relire
- [x] Hugues: Manuel utilisateur SW
- [x] Hugues: Faire la démo
- [x] Hugues: Finir mettre au propre le code
- [x] Hugues: Relire
